apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tls.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secrets.yaml
  - openconnect-secret.yaml
  - tls.yaml
