---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: "27.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  targetNamespace: monitoring
  values:
    annotations:
      meta.helm.sh/release-name: prometheus-operator-crds
      meta.helm.sh/release-namespace: monitoring
    alertmanagerconfigs:
      enabled: true
    alertmanagers:
      enabled: true
    podmonitors:
      enabled: true
    probes:
      enabled: true
    prometheusagents:
      enabled: true
    prometheuses:
      enabled: true
    prometheusrules:
      enabled: true
    scrapeconfigs:
      enabled: true
    servicemonitors:
      enabled: true
    thanosrulers:
      enabled: true
