apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    TRUENAS_PASSWORD: ENC[AES256_GCM,data:XPOq0aB7npH/ogI=,iv:vvEMXpX+TeSvF1e+bKvecEt8GkPshWi1tSJOu2CUtb0=,tag:fLo/eNlk1uRlDS9nYPIr1w==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:kb6RObCANybnOTTHeRJwYbS2Xx9q/3nftTpTW7QSVH8ZMjjZeawsyES92byTzu5aOcHwstz10HIOPg6wF3VdnSn9,iv:m2EGQrnjM1yUmevGzB9rCkeYH/282JDrrO1Bj7iBZII=,tag:ZkoY+FryVVLmiZL7jUc1NA==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSjJHSlJ0OXU3RlFGc1pG
            TTBzVzhoWUVvT3V6VnpFTHlmRCtXMTk1bW1zCmtYQm1tS2p2eEtFY0lXc0w0M0NC
            YVpTMmZHR05WM3JjRHdxRVF6SWliUmMKLS0tIFdNZ2tXd1o5QlNEeWZ0SGQrbWFv
            b0pVWGZ4aG50VWV2bFdRa2pDVWYyZUUKhoJGj8PijTj/luwcEk6zojWO79O47WZc
            OWxa8qi1XlY3I1TakIgRF8672x6rzdqiwM+upOLj1lS1LHeQXGlGmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T17:19:48Z"
    mac: ENC[AES256_GCM,data:jRvezGzz5UrMdtU3MtKvlNv8EQc5kPe2sHQx1UbJZWr5DLIZJOiGTfJ6KWqSJyrZjBYXjaY2MkQXPDfSICVgy3L+wSO3nDHebUFud2FBnSpf7clpT0vyLbZDA1Q4QRWrHdXCbXvBQqtiv+QgN8h1f6/Cf1qSPNFx2xik5Amodvc=,iv:bjig4vEFA5dA4R2kjao9qGjqzJ1icD+4SRrNQfakzHw=,tag:UcGB4Q//CMFgv7gSEmopgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
