---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./trust-manager
  - ./cloudnativepg
#  - ./falco
  - ./kyverno
  - ./mariadb-operator
  - ./redis-operator
  - ./renovate
