# _lib/apps/wallabag/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ob-archiver.yaml
  - ob-recovery.yaml
  - database.yaml
